export const data = [
  {
    id: 0,
    compIcon: '../assets/imgs/scoot.svg',
    compIconBg: 'rgb(233, 146, 15)',
    posted: '5h ago',
    jobType: 'Full Time',
    jobTitle: 'Senior Software Engineer',
    jobSubTitle: 'Scoot',
    jobLocation: 'United Kingdom',
  },
  {
    id: 1,
    compIcon: '../assets/imgs/blogr.svg',
    compIconBg: 'rgb(228, 78, 35)',
    posted: '20h ago',
    jobType: 'Part Time',
    jobTitle: 'Haskell and PureScript Dev',
    jobSubTitle: 'Blogr',
    jobLocation: 'United State',
  },
  {
    id: 2,
    compIcon: '../assets/imgs/vector.svg',
    compIconBg: 'rgb(53, 53, 63)',
    posted: '1d ago',
    jobType: 'Part Time',
    jobTitle: 'Midlevel Backend Enginner',
    jobSubTitle: 'Vector',
    jobLocation: 'Russia',
  },
  {
    id: 3,
    compIcon: '../assets/imgs/officelite.svg',
    compIconBg: 'rgb(46, 80, 195)',
    posted: '2d ago',
    jobType: 'Full Time',
    jobTitle: 'Senior Application Engineer',
    jobSubTitle: 'Office Lite',
    jobLocation: 'Japan',
  },
  {
    id: 4,
    compIcon: '../assets/imgs/pod.svg',
    compIconBg: 'rgb(20, 31, 49)',
    posted: '2d ago',
    jobType: 'Part Time',
    jobTitle: 'Remote DevOps Engineer',
    jobSubTitle: 'Pod',
    jobLocation: 'Thailand',
  },
  {
    id: 5,
    compIcon: '../assets/imgs/creative.svg',
    compIconBg: 'rgb(80,24,79)',
    posted: '4d ago',
    jobType: 'Part Time',
    jobTitle: 'Desktop Support Manager',
    jobSubTitle: 'Creative',
    jobLocation: 'Germany',
  },
  {
    id: 6,
    compIcon: '../assets/imgs/pomodoro.svg',
    compIconBg: 'rgb(71, 34, 199)',
    posted: '1w ago',
    jobType: 'Full Time',
    jobTitle: 'iOS Engineer',
    jobSubTitle: 'Pomodoro',
    jobLocation: 'United States',
  },
  {
    id: 7,
    compIcon: '../assets/imgs/maker.svg',
    compIconBg: 'rgb(37, 64, 125)',
    posted: '1w ago',
    jobType: 'Part Time',
    jobTitle: 'Senior EJB Developer',
    jobSubTitle: 'Maker',
    jobLocation: 'United Kingdom',
  },
  {
    id: 8,
    compIcon: '../assets/imgs/coffeeroasters.svg',
    compIconBg: 'rgb(243, 222, 203)',
    posted: '2d ago',
    jobType: 'Part Time',
    jobTitle: 'Senior Frontend Developer',
    jobSubTitle: 'Coffeeroasters',
    jobLocation: 'Singapore',
  },
  {
    id: 9,
    compIcon: '../assets/imgs/mastercraft.svg',
    compIconBg: 'rgb(31,31,31)',
    posted: '2w ago',
    jobType: 'Freelance',
    jobTitle: 'App & Website Designer',
    jobSubTitle: 'Mastercraft',
    jobLocation: 'United States',
  },
  {
    id: 10,
    compIcon: '../assets/imgs/crowdfund.svg',
    compIconBg: 'rgb(55, 199, 145)',
    posted: '1mo ago',
    jobType: 'Part Time',
    jobTitle: 'Fullstack Developer',
    jobSubTitle: 'Crowdfund',
    jobLocation: 'New Zealand',
  },
  {
    id: 11,
    compIcon: '../assets/imgs/typemaster.svg',
    compIconBg: 'rgb(239, 104, 23)',
    posted: '1mo ago',
    jobType: 'Part Time',
    jobTitle: 'Technical Lead Engineer',
    jobSubTitle: 'Typemaster',
    jobLocation: 'United Kingdom',
  },
];
